version: "3.9"
services:
  postgres:
    image: postgres:13-alpine
    container_name: pg_tasks
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lusm123
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: main
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
      - ./.docker/setup.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:

